event_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registeration.urls'))
]

registeration/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'registeration'

urlpatterns = [
    path('person/<int:person_pk>/', views.person_detail_view, name="person_detail"),
    path('all-tickets/<int:event_group_pk>/', views.all_tickets),
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('user_page/' , views.user_page_view, name="user_page"),
    path('event_group/<int:event_group_pk>/', views.event_group_view, name="event_group"),
    path('event/<int:event_pk>/purchase/', views.purchase_view, name="purchase"),
    path('verify/', views.verify_view, name="verify"),
    path('error/', views.error, name="error"),
    path('api/discount_check/<int:event_group_pk>/', views.discount_check_api, name="discount_check"),
    path('', views.home_view, name="home")
]

registeration/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



class EventGroup(models.Model):
    name = models.CharField(max_length=100)
    detail = models.TextField(max_length=1000)

    def __str__(self):
        return  self.name

class Person(models.Model):
    user = models.ForeignKey(User ,on_delete=models.CASCADE)

    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    national_id = models.CharField(max_length = 100)
    phone_number = models.CharField(max_length = 100)
    email = models.EmailField(max_length = 100)

    person_type = models.IntegerField(default = 0)

    detail_type = models.IntegerField(default = 4)

    guide_id = models.CharField(null=True, blank=True, max_length = 100)

    university = models.CharField(null=True, blank=True, max_length = 100)
    study_field = models.CharField(null=True, blank=True, max_length = 100)
    student_id = models.CharField(null=True, blank=True, max_length = 100)

    agancy = models.CharField(null=True, blank=True, max_length = 100)
    city = models.CharField(null=True, blank=True, max_length = 100)

    hotel = models.CharField(null=True, blank=True, max_length = 100)
    #city = models.CharField(default="-", max_length = 100)

    def __str__(self):
        return self.first_name + " " + self.last_name

    def is_staff(self):
        return self.person_type == 1

    def person_type_show(self):
        type_dictionary = {
        0 : "راهنمای گردشگری",
        1 : "دانشجو",
        2 : "کارمند دفاتر مسافرتی / تور اپراتور",
        3 : "کارمند هتل",
        4 : "آزاد",
        }

        if self.detail_type in type_dictionary:
            return type_dictionary[self.detail_type]
        else:
            return "خطا"

class Event(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(default=5000)#tooman.
    capacity = models.IntegerField(default=30)#People
    address = models.TextField(max_length=1000, blank=True, null=True)
    date = models.TextField(max_length=1000, blank=True, null=True)
    time = models.TextField(max_length=1000, blank=True, null=True)
    detail = models.TextField(max_length=1000)

    file_name = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    event_group = models.ForeignKey(EventGroup, on_delete=models.PROTECT)

    def __str__(self):
        return self.event_group.name + " : " + self.name

class Invoice(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    person = models.ForeignKey(Person, on_delete=models.PROTECT)
    event  = models.ForeignKey(Event, on_delete=models.PROTECT)
    amount = models.IntegerField(default=0)# tooman
    active = models.IntegerField(default=1)# 0: deactive     , 1: active
    paid   = models.IntegerField(default=0)# 0: never_paid , 1: $$$

    authority   = models.CharField(max_length = 200, default = "none")
    refid       = models.CharField(max_length = 200, default = "none")

    discount_pk = models.IntegerField(default=0)

    def is_successful(self):
        return self.status == 0

    def __str__(self):
        if self.paid:
            return str(self.amount) + "$"
        if not self.active:
            return "خارج از دور"
        return "در حال پرداخت"


    def show_discount_detail(self):
        if self.discount_pk:
            discount = Discount.objects.get(pk=self.discount_pk)
            return str(discount)
        else:
            return "بدون استفاده از تخفیف"

class Discount(models.Model):
    percent = models.IntegerField(default=0)
    #event   = models.ForeignKey(Event, on_delete=models.CASCADE)
    event_group = models.ForeignKey(EventGroup, on_delete=models.PROTECT)
    code    = models.CharField(max_length=100)
    capacity = models.IntegerField(default=0)

    detail = models.CharField(max_length=100)

    is_active = models.BooleanField(default=True)
    def __str__(self):
        return str(self.percent) + "% " + self.detail

class Visitor(models.Model):
    ip = models.CharField(max_length=20)
    visit_time = models.DateTimeField(auto_now=True)

registeration/views.py
from django.contrib.auth import  login, logout
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import datetime
from furl import furl
from zeep import Client
import json

from django.contrib.auth.models import User

from django.contrib.staticfiles.templatetags.staticfiles import static
from .models import Person, Invoice, Event, Discount, EventGroup, Visitor

from . import secret

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

def farsi_to_english_digit(number_string):
    dic = {
    "۰" : "0",
    "۱" : "1",
    "۲" : "2",
    "۳" : "3",
    "۴" : "4",
    "۵" : "5",
    "۶" : "6",
    "۷" : "7",
    "۸" : "8",
    "۹" : "9",
    }
    for digit in dic:
        number_string = number_string.replace(digit, dic[digit])
    return number_string


def register_post_validator(post):
    def string_type_validator(field_name, field_max_length):
        if field_name not in post:
            return "field %s is missing"%field_name
        if len(post[field_name]) < 2 :
            return "field %s is too short"%field_name
        if len(post[field_name]) > field_max_length :
            return "field %s is too long"%field_name
        return ""

    for checking_field in ["first_name", "last_name", "national_id", "phone_number","email",]:
        res = string_type_validator(checking_field, 99)
        if res:
            return res
    ### missing check email $$$
    if len(post['national_id']) != 10:
        return "short or long national_id"

    for digit in post["national_id"]:
        if digit not in "0123456789۰۱۲۳۴۵۶۷۸۹":
            return "non numerical national_id"

    for digit in post['phone_number']:
        if digit not in "0123456789۰۱۲۳۴۵۶۷۸۹+":
            return "non numerical phone_number"

    if post['detail_type'] not in ['0','1','2','3', '4']:
        return "bad format of detail_type"

    type = int(post['detail_type'])

    if type == 0:
        # res = string_type_validator("guide_id", 99)
        # if res:
        #     return res
        comment = "do nothing"

    elif type == 1:
        for checking_field in ["university", "study_field", "student_id"]:
            res = string_type_validator(checking_field, 99)
            if res:
                return res
        for digit in post["student_id"]:
            if digit not in "0123456789۰۱۲۳۴۵۶۷۸۹":
                return "bad student_id format"

    elif type == 2:
        for checking_field in ["agency", "city",]:
            res = string_type_validator(checking_field, 99)
            if res:
                return res

    elif type == 3:
        for checking_field in ["hotel", "city",]:
            res = string_type_validator(checking_field, 99)
            if res:
                return res

    return ""


def register_view(request):
    template = 'registeration/register.html'
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('registeration:event_group', kwargs={'event_group_pk':1}))
    else:
        if request.method == 'POST':
            #validation of data
            error_message = register_post_validator(request.POST)
            if not error_message:
                # if user didnt registered before
                if not Person.objects.filter(national_id = request.POST['national_id']).exists():
                    # then create the user
                    user = User(
                        username = request.POST['email'],
                    )
                    user.set_password(request.POST['national_id'])
                    user.save()
                    person = Person(user = user)
                    person.first_name = request.POST['first_name']
                    person.last_name = request.POST['last_name']
                    person.national_id = request.POST['national_id']
                    person.phone_number = request.POST['phone_number']
                    person.email = request.POST['email']
                    person.detail_type = int(request.POST['detail_type'])

                    type = person.detail_type
                    if type == 0:
                        if 'guide_id' in request.POST:
                            if request.POST['guide_id']:
                                person.guide_id = request.POST['guide_id']
                    elif type == 1:
                        person.university = request.POST['university']
                        person.study_field = request.POST['study_field']
                        person.student_id = request.POST['student_id']
                    elif type == 2:
                        person.agency = request.POST['agency']
                        person.city = request.POST['city']
                    elif type == 3:
                        person.hotel = request.POST['hotel']
                        person.city = request.POST['city']
                    elif type == 4:
                        comment = "do nothig"
                    else:
                        comment = "should not happen"
                    person.save()
                    login(request, user)
                    return HttpResponseRedirect(reverse('registeration:event_group', kwargs={'event_group_pk':1}))

                else:
                    return render(request,template,{'error_message': "کد ملی از قبل وجود دارد"})
            else:
                return render(request,template,{'error_message': error_message})
        else:
            #load page for first time
            return render(request,template)

def login_view(request):
    template = 'registeration/login.html'
    if request.user.is_authenticated :
        return HttpResponseRedirect(reverse('registeration:event_group', kwargs={'event_group_pk':1}))

    if request.method == 'POST':
        if 'username' in request.POST and 'password' in request.POST:
            if User.objects.filter(username=request.POST['username']).exists():
                user = User.objects.get(username=request.POST['username'])
                if user.check_password(request.POST['password']):
                    login(request, user)
                    return HttpResponseRedirect(reverse('registeration:event_group', kwargs={'event_group_pk':1}))
                else:
                    return render(request, template, {'error_message': 'رمز عبور نادرست است'})
            else:
                return render(request, template, {'error_message': 'ایمیل شما در سایت ثبت نشده است'})
        else:
            return render(request, template, {'error_message': 'missing username or password in json'})

    return render(request, template)


def user_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('registeration:login'))
    template = 'registeration/user_page.html'
    event_groups = EventGroup.objects.all()
    person = Person.objects.get(user=request.user)
    tickets = Invoice.objects.filter(paid=1, person=person)
    return render(request,template,{'event_groups' : event_groups, 'tickets' : tickets})

def home_view(request):
    ip=get_client_ip(request)
    if(ip != '127.0.0.1'):
        Visitor.objects.create(ip=get_client_ip(request))
    template = 'registeration/home.html'
    return render(request,template)

def verify_view(request):
    MERCHANT = secret.MERCHANT
    if request.GET.get('Status') == 'OK':
        authority = request.GET['Authority']
        try:
            invoice = Invoice.objects.get(authority=authority)
        except:
            return HttpResponseRedirect(reverse('registeration:error'))

        client = Client('https://www.zarinpal.com/pg/services/WebGate/wsdl')
        result = client.service.PaymentVerification(MERCHANT, invoice.authority, invoice.amount)
        if result.Status == 100 or result.Status == 101:
            #payed
            invoice = Invoice.objects.get(authority=request.GET['Authority'])
            invoice.refid = result.RefID
            invoice.active = 1
            invoice.paid = 1
            invoice.save()

            for o_invoice in Invoice.objects.filter(person=invoice.person, event=invoice.event, active=1, paid=0):
                o_invoice.active=0
                o_invoice.save()
            return HttpResponseRedirect("%s?payment_success=true" % reverse('registeration:event_group', kwargs={'event_group_pk':1}))

        else:
            #failed to pay
            return HttpResponseRedirect("%s?payment_error=پرداخت ناموفق" % reverse('registeration:event_group', kwargs={'event_group_pk':1}))

    return HttpResponseRedirect("%s?payment_error=پرداخت ناموفق" % reverse('registeration:event_group', kwargs={'event_group_pk':1}))


def purchase_view(request, event_pk):
    invoice_cleaner()
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('registeration:login'))

    template = 'registeration/user_page.html'
    try :
        person = Person.objects.get(user=request.user)
    except:
        return render(request, template, {'error_message': 'bad person'})
    try:
        event  = Event.objects.get(pk = event_pk)
    except:
        return render(request, template, {'error_message': 'همچین رویدادی وجود ندارد'})

    if request.method != 'POST':
        return error(request)
    if 'discount_code' not in request.POST:
        return error(request)

    if request.POST['discount_code']:
        try:
            discount = Discount.objects.get(event_group=event.event_group, code=request.POST['discount_code'])#debug event
            discount_pk = discount.pk
        except:

registeration/templates/registeration/all_tickets.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>رویداد های آکادمیک</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
</head>
<body style="background-color: #eeeeee" dir="rtl">
    <div class="ui container" style="margin: 20px auto;">
        <div class="ui segment">
        {% for ticket_group in ticket_groups %}
            <div class="ui header" style="text-align: center;">
                {{ ticket_group.name }} - {{ ticket_group.count }} نفر
            </div>
            <table class="ui single line striped selectable unstackable table center aligned">
                <tr>
                    <th>
                      تاریح خرید
                    </th>
                    <th>
                        نام و نام خانوادگی
                    </th>
                    <th>
                      شماره تماس
                    </th>
                    <th>
                      پست الکترونیک
                    </th>
                    <th>
                      شماره بلیط
                    </th>
                    <th>
                        مبلغ پرداخت شده
                    </th>
                </tr>
                {% for ticket in ticket_group.tickets %}
                <tr>
                    <td>
                      {{ ticket.created_date }}
                    </td>
                    <td>
                        <a href="{% url 'registeration:person_detail' ticket.person.pk %}">{{ ticket.person.first_name }} {{ ticket.person.last_name }}</a>
                    </td>
                    <td>
                      {{ ticket.person.phone_number }}
                    </td>
                    <td>
                      {{ ticket.person.email }}
                    </td>
                    <td>
                      {{ ticket.refid }}
                    </td>
                    <td>
                        {{ ticket }}
                    </td>
                </tr>
                {% endfor %}
            </table>
        {% endfor %}
        </div>
    </div>
</body>
</html>

registeration/templates/registeration/event.html
<p>
  {{event.name}}
</p>

<p>
  {{ event.price }} تومان
</p>
<form action="{% url 'registeration:purchase' event.pk %}" method="post">
  {% csrf_token %}
  <input type="text" name="discount_code" value="">
  <input type="submit" name="" value="خرید‍‍‍">
</form>

registeration/templates/registeration/event_group.html
<!DOCTYPE html>

{% load static %}

<html>

    <head>

        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>رویداد های آکادمیک</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'event_group/event_group.css' %}"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/axios@0.18.0/dist/axios.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
        

    </head>




    <body>

        <div id="main">
          <div class="ui active dimmer" v-if="loading">
              <div class="ui text loader"> <span id="load">... در حال بارگذاری</span> </div>
          </div>






            <div class="ui basic modal">

                <div class="ui active dimmer" v-if="loading">
                    <div class="ui text loader"> <span id="load">... در حال بارگذاری</span> </div>
                </div>
                <div id="modal_header">کد تخفیف خود را وارد کنید</div>
                <div v-if="discountError" class="ui message error" style="width: 300px; margin: auto; text-align: center">
                  کد تخفیف نامعتبر است
                </div>
                <div id="modal_content">

                        <input @keypress.enter="discountValidation" type="text" v-model="discountCode" name="discount" id="discount" placeholder="کدتخفیف">
                        <button @click="discountValidation" id="activate_discount">ثبت</button>
                    
                </div>
                    
            </div>



















            <div id="fixed_menu">

                <a id="sign_fm" href="#">
                    پروفایل
                </a>

                <a id="exit_fm" href="{% url 'registeration:logout' %}">
                    خروج
                </a>
                
                <a href="{% url 'registeration:home' %}">
                    <img id="logo_fm" src="{% static 'register/photo1.jpg' %}">
                </a>
    
            </div>

            <div id="content">
                <div id="three_steps">


                    <div class="ui three top attached mini steps">

                        <div class="step">

                            <i class="pencil alternate icon" id="i1"></i>

                            <div class="content">

                                <div class="title" id="t1">ثبت نام</div>

                            </div>

                        </div>
        
                        <div class="active step">

                            <i class="map signs icon" id="i2"></i>

                            <div class="content">

                                <div class="title" id="t2">انتخاب رویداد</div>

                            </div>

                        </div>
        
                        <div class="disabled step">

                            <i class="payment icon"></i>

                            <div class="content">

                                <div class="title" id="t3">دریافت بلیط</div>

                            </div>

                        </div>
        
                    </div>


                </div>
                {% if payment_error %}
                <div class="ui message error" style="width: 60%; text-align: right; margin: 10px auto;">
                    {{ payment_error }}
                </div>
                {% endif %}
                {% if payment_success %}
                <div class="ui message" style="width: 60%; text-align: right; margin: 10px auto;">
                    با موفقیت پرداخت شد
                </div>
                {% endif %}
                <div id="main_content">

                    <form class="ui card event_card" :action="event.form_action_url" method="post" v-for="event in events">

                    {% csrf_token %}
                          <input type="hidden" name="discount_code" :value="discountPercent ? discountCode : ''" />
                    {% verbatim %}
                        <div class="content content_header">

                            <h3 class="ui center aligned header title_city">
                                {{ event.name }}
                            </h3>

                        </div>

                        <div class="content event_content">
                            
                          <h4 class="ui header">اطلاعات رویداد</h4>
                          <div class="ui small feed">
                            <div class="event">
                              <div class="content">
                                <div class="summary" style="line-height: 25px; font-family: Yekan; font-size: 16px; font-weight: normal; text-align: right;">
                                    آدرس: {{ event.address }}
                                    <br />
                                    <br />
                                    تاریخ: {{ event.date }}
                                    <br />
                                    <br />
                                    زمان: {{ event.time }}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>

                        <div class="extra content">
                            <div style="font-family: Yekan; font-weight: 700; text-align: center; font-size: 18px; padding: 20px; color: #444444;">
                                <template v-if="discountPercent">
                                  قیمت: <span style="text-decoration: line-through; color: #aaaaaa">{{ event.price | toPersinaNumber }}</span> {{ event.price - event.price / 100 * discountPercent }} تومان
                                </template>
                                <template v-else>
                                  قیمت: {{ event.price | toPersinaNumber }} تومان
                                </template>
                            </div>
                            <div v-if="discountPercent" dir="rtl" style="font-family: Yekan; font-weight: 700; text-align: center; font-size: 18px; padding-bottom: 20px; color: #444444;">
                              کد تخفیف: {{ discountCode }}
                            </div>
                            <button class="ui animated button pay_event" tabindex="0">

                                <div class="visible content v1"><i class="payment icon i4"></i>پرداخت</div>

                                <div class="hidden content">
                                    <i class="right arrow icon"></i>
                                </div>

                            </button>

                            <div class="ui button goto_discount">
                                کد تخفیف
                                <i class="gift icon i5"></i>
                            </div>

                        </div>

                    </form>






















                    <!-- <div class="left_content" v-for="event in events">

                        <h3 class="ui center aligned block header" id="title_city1">
                            {{ event.name }}
                        </h3>

                        <div id="main_left_content">
                            <template v-if="discountPercent">
                                {{ event.price }} - {{ event.price - event.price / 100 * discountPercent }}
                            </template>
                            <template v-else>
                                {{ event.price }}
                            </template>
                        </div>

                        <div id="left_bottom">

                            <button id="goto_discount" onclick="window.location.href='#input_text'">کد تخفیف</button>

                            <div class="ui animated button" id="pay_tehran" tabindex="0">

                                <div class="visible content" id="v1"><i class="payment icon" id="i4"></i>پرداخت</div>

                                <div class="hidden content">
                                    <i class="right arrow icon"></i>
                                </div>

                            </div>

                        </div>

                    </div>


                    <div id="input_text">
    
                        <div v-if="discountError" class="ui message error">
                            {{ discountError }}
                        </div>

                        <input type="text" v-model="discountCode" name="discount" id="discount" placeholder="کدتخفیف">
                        <button @click="discountValidation" id="activate_tehran">ثبت</button>



                    </div> -->
                    {% endverbatim %}

                </div>

            </div>
        </div>

        <script>
            new Vue({
                el: '#main',
                data: {
                    events: [
                    {% for event in events %}
                        {
                            name: '{{event.name}}',
                            detail: `{{event.detail}}`,
                            address: `{{event.address}}`,
                            date: `{{event.date}}`,
                            time: `{{event.time}}`,
                            price: {{ event.price }},
                            form_action_url: '{% url 'registeration:purchase' event.pk %}'
                        },
                    {% endfor %}
                    ],
                    discountPercent: null,
                    loading: false,
                    discountCode: null,
                    discountError: null,
                },
                filters: {
                  toPersinaNumber: function(value) {
                    return String(value).replace(/0/g, '۰')
                                    .replace(/1/g, '۱')
                                    .replace(/2/g, '۲')
                                    .replace(/3/g, '۳')
                                    .replace(/4/g, '۴')
                                    .replace(/5/g, '۵')
                                    .replace(/6/g, '۶')
                                    .replace(/7/g, '۷')
                                    .replace(/8/g, '۸')
                                    .replace(/9/g, '۹')
                  }
                },
                methods: {
                    insertBreaks: function(value) {
                        if (!value) return ''
                        return value.replace(/\n/g, ' <br/> ')
                    },
                    discountValidation(){
                        const vinst = this;
                        if(this.discountCode){
                            this.loading = true;
                            axios.post('{{ discount_check_url }}',{
                              discount_code: vinst.discountCode
                            },{
                                headers: {
                                  'Content-Type': 'application/json'
                                }
                            }).then(function(response) {
                                console.log(response.data)

                                if(response.data.result == 'ok'){
                                    vinst.discountPercent = response.data.percent;
                                    $('.ui.modal')
                                    .modal('hide');
                                } else {
                                    vinst.discountError = response.data.error_message;
                                }
                                vinst.loading = false;
                            })
                        }
                    }
                }
            })


            $(document).ready(function(){
                $(".ui.button.goto_discount").click(function(){
                    $('.ui.modal')
                    .modal('show');
                });
            });
        </script>
    </body>




</html>

registeration/templates/registeration/user_page.html
{% if error_message%}
<p style="color:red">{{ error_message }}</p>
{% endif %}
<p>no place like home</p>
<ul>
  {% for event_group in event_groups %}
  <li><a href="{% url 'registeration:event_group' event_group.pk %}">{{ event_group.name }}</a></li>
  {% endfor %}
</ul>

<h1>your tickets</h1>
{% for ticket in tickets %}
  <p>رویداد : </p>
  <p>{{ticket.event.name}}</p>
{% endfor %}